### ISSUE TITLE
Hello Matthew

### ISSUE THREAD

**Issue by abarberenaCPDS** [maishiroma/MCServerBootstrap#12]
My name is Abe, I was an attendee of the Cloud natives meetup group organized by the NB team a couple years ago.

I am not a recruiter, I am a Sw Arch, I would like to talk to you about a job opportunity. I could not find your email and that’s why I am reaching out by these means. If you’re interested please let me know so we can discuss further.

**Comment by maishiroma** [comment]
Hello, Abe! I think this is a first time someone reached out to me on a GitHub Issue specifically haha. Ah, you were in the CloudNatives group! It's good to be reacquainted with you.

Do you have a Linkedln? It would be best to reach out to me through there, since I'm a bit privy with emails nowadays. Here's a [link](https://www.linkedin.com/in/maishiroma/) to my profile.

Thanks for the comment!

**Comment by abarberenaCPDS** [comment]
Hey @maishiroma 👋 , nice to get an answer from you. I purposely choose this way to reach out, I knew I would be successful this way in reaching out. Hmm, I do not use LinkedIn, however, I would like to talk to you. Can you reach out to me: seven one four 6794844?

**Comment by maishiroma** [comment]
Sorry for the late reply, I've been a bit busy on my side. I'll reach out to you once I have some free time on my end. Appreciate the message!

**Comment by abarberenaCPDS** [comment]
Hey @maishiroma, no worries, I got busy too, however, I thought of you and decided to reach out due to one of your videos about azure devops pipelines. I am working on a couple projects that are using computer vision, containers and so on. I think you would be a good help, so, should you get a moment available or circumstances change, do not hesitate to contact me.
